# Generated by Django 4.2.6 on 2023-10-09 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.IntegerField()),
                ('sname', models.CharField(max_length=20)),
                ('num', models.BigIntegerField()),
                ('mail', models.EmailField(max_length=254)),
                ('dob', models.DateField()),
            ],
        ),
    ]
